/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiResponseMemberResponse
 */
export interface ApiResponseMemberResponse {
  /**
   *
   * @type {string}
   * @memberof ApiResponseMemberResponse
   */
  message?: string;
  /**
   *
   * @type {MemberResponse}
   * @memberof ApiResponseMemberResponse
   */
  result?: MemberResponse;
}
/**
 *
 * @export
 * @interface MemberResponse
 */
export interface MemberResponse {
  /**
   *
   * @type {number}
   * @memberof MemberResponse
   */
  memberNo?: number;
  /**
   *
   * @type {string}
   * @memberof MemberResponse
   */
  provider?: string;
  /**
   *
   * @type {string}
   * @memberof MemberResponse
   */
  providerId?: string;
  /**
   *
   * @type {string}
   * @memberof MemberResponse
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof MemberResponse
   */
  memberState?: MemberResponseMemberStateEnum;
  /**
   *
   * @type {string}
   * @memberof MemberResponse
   */
  hint1?: string;
  /**
   *
   * @type {string}
   * @memberof MemberResponse
   */
  hint2?: string;
  /**
   *
   * @type {string}
   * @memberof MemberResponse
   */
  createDt?: string;
}

export type MemberResponseMemberStateEnum =
  | "OAUTH_ONLY"
  | "NORMAL"
  | "SUSPENDED"
  | "DELETED";
